// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditListController from "./edit_list_controller"
application.register("edit-list", EditListController)

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MovieController from "./movie_controller"
application.register("movie", MovieController)

import ShowMoreController from "./show_more_controller"
application.register("show-more", ShowMoreController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)
