// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditListController from "./edit_list_controller"
application.register("edit-list", EditListController)

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertReviewController from "./insert_review_controller"
application.register("insert-review", InsertReviewController)

import MovieController from "./movie_controller"
application.register("movie", MovieController)

import ShowFormlistController from "./show_formlist_controller"
application.register("show-formlist", ShowFormlistController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)
