meta_name: "Ottter"
meta_title: "Ottter - Discover and Recommand"
meta_description: "Give and receive recommendations easily and quickly with Ottter. Store them all in one place!"
meta_image: "otter.png"
